### ISSUE TITLE
help needed + questions

### ISSUE THREAD

**Issue by Leeskjold** [Michal2SAB/Stick-Arena-Private-Server#1]
Hi! I'm not too sure how to go about this too well, 

1. should i use this repository on it's own or should i follow the steps by Kevin (https://github.com/6Kevin/StickEMU) and append files? the "dist" directory is missing. 

2. should i edit the index.php to say sab.swf or rename sab to game.swf

3. should i paste just the contents of the \stickarena directory in htdocs or just the whole folder fine or doesn't matter?

**Comment by Michal2SAB** [comment]
Kevin's repository is for an old version of stick arena (pre ballistick and dimensions). If that's what you want to work with, follow his instructions. This repository is totally different as it's for ballistick (newer stick arena)

1. You need to compile the source code (java classes in src/ballistickemu) and make it into a BallistickEMU.jar file which will be located in ballistick/dist directory.
2. It should be the name of the SWF that is inside the directory so that's my bad, I'll rename it to sab.swf
3. The entire stickarena directory can be passed to htdocs on your localhost server or wherever you wanna host it on the web

**Comment by Leeskjold** [comment]
Thanks for the reply! unfortunately i am having some trouble building the java classes from source, i get "Main.java:11: error: package ballistickemu.Lobby does not exist" along with the other folders, it's like it's not being seen. I used javac "Main.java" in /src

**Comment by Michal2SAB** [comment]
Try compiling it with netbeans

**Comment by Leeskjold** [comment]
ah sorry to keep hounding you with questions man! I'm having a manifest error now, although there is a manifest file in there, i peek in the built jar and it's structured like "/meta-inf and /ballistickemu along with main.class and all relating folders like lobby and game. is the structure correct or am i overlooking something? 

edit: structure looks good according to oracle, but the manifest issue still persists. no main manifest attribute, in dist\BalliStickEMU.jar

edit again: i have fixed the manifest, but now i am being thrown "java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.sql.Connection.isClosed()" because "ballistickemu.Tools.DatabaseTools.db_Connection" is null
        at ballistickemu.Tools.DatabaseTools.executeSelectQuery(DatabaseTools.java:110)
        at ballistickemu.Types.StickShop.PopulateShop(StickShop.java:33)
        at ballistickemu.Main.main(Main.java:68)"
        
        i am not sure how to fix this as my java knowledge is very limited. I'm surprised i got as far as i did hah.

**Comment by Michal2SAB** [comment]
The error you're getting is from running the jar right? If yes then it's most likely because you're not running the jar on any localhost or vps etc. It can't read the database because it can't connect to it. If you are running a server then check if you have imported the database and configured it in stick_arena.php file (linked to it properly, with your db password, user and db name)

**Comment by Leeskjold** [comment]
yes i can confirm i have linked everything to the best of my knowledge, my db name is 'ballistickemu' with import of the structure.. and the user I made for it is 'weewee'  there is more to this but github cuts my message so here's a drive link to the full. https://drive.google.com/file/d/1GLMCEO63rwFfEcIB474EMO25I8Bf3N-7/view?usp=share_link

stickarena.php


<?php
//My login Script
// mysql connection variables
require_once('./class.rc4crypt.php');
$host = 'localhost';
$dbuser = 'weewee';
$dbpass = 'MYPASS';
$dbname = 'ballistickemu';
$table = 'users';
//
// connect to db


config.properties


server_IP = localhost
server_Port = 1138
server_maxPlayers = 100
db_user = weewee
db_pass = MYPASS
db_server = localhost
db_database = ballistickemu


databasetools in/src before compiling

public class DatabaseTools {
    private static Connection db_Connection = null;
    public static String user = "weewee";
    public static String pass = "MYPASS";
    public static String server = "localhost";
    public static String database = "ballistickemu";
    public static final ReentrantLock lock = new ReentrantLock();

main.java before compile

public class Main {
    public static String IP = "localhost";
    private static int PORT = 1138;
    public static int maxPlayers = 100; // 100 default, but configureable via props
    private static LobbyServer LS;

**Comment by Michal2SAB** [comment]
Then you're not hosting your server properly.

**Comment by ctimko1493** [comment]
Lee did you ever figure this out? I need help also (with compiling)

**Comment by Leeskjold** [comment]
I'm still working on it myself, I got some part of the compiled stuff
working but it's rough

**Comment by ctimko1493** [comment]
Do you have discord Lee maybe we could help eachother out? I'm having a manifest error with the jar like you did but I have a fully running 558 server, just trying to get the 588 working

**Comment by Leeskjold** [comment]
I do! I'll get back with you soon, let's try and get it working sometime!

**Comment by ctimko1493** [comment]
Ok, wingy#1853 is my discord username and https://discord.gg/TTB2RSnr is my server

**Comment by ctimko1493** [comment]
How did you end up getting your .jar file to run properly??

**Comment by Leeskjold** [comment]
Ohh! I had to generate my own manifest i can't remember what it was, I'll
add you on discord (sorry I'm a bit of a scatterbrain hah)
