### ISSUE TITLE
can you fix this things

### ISSUE THREAD

**Issue by Migueli000** [Michal2SAB/Stick-Arena-Private-Server#4]
1. i can't login : he getting this message there was a problem while attempting to authenticate your login - please try again.
![dssadssd](https://github.com/Michal2SAB/Stick-Arena-Private-Server/assets/152816074/db268fcd-b263-4130-8d8b-58002544dacd)

2. health bug : the glitch is that when the person is low on life it doesn't change the icon that icon of the heart losing blood
![Captura de tela 2024-05-26 140231](https://github.com/Michal2SAB/Stick-Arena-Private-Server/assets/152816074/b7ae1991-9e81-4809-94e8-3fcca4b357fa)

**Comment by andre-jar** [comment]
> 1. i can't login : he getting this message there was a problem while attempting to authenticate your login - please try again.
>        ![dssadssd](https://private-user-images.githubusercontent.com/152816074/333898602-db268fcd-b263-4130-8d8b-58002544dacd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDM3MDgsIm5iZiI6MTcxNzM0MzQwOCwicGF0aCI6Ii8xNTI4MTYwNzQvMzMzODk4NjAyLWRiMjY4ZmNkLWIyNjMtNDEzMC04ZDhiLTU4MDAyNTQ0ZGFjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDAwOWViM2UxNjE3ZmZjZmYyNzJhYmMyODUzMTg2MmQzYWUzZWFmYzNjY2E2NzdlM2JkMjM5ZWQyODQyOGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kLETiqJ_G_Cvv3xRAFVdu6PGg6I49FCBAj1EDk_rRpc)
> 
>     2. health bug : the glitch is that when the person is low on life it doesn't change the icon that icon of the heart losing blood
>        ![Captura de tela 2024-05-26 140231](https://private-user-images.githubusercontent.com/152816074/333898571-b7ae1991-9e81-4809-94e8-3fcca4b357fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDM3MDgsIm5iZiI6MTcxNzM0MzQwOCwicGF0aCI6Ii8xNTI4MTYwNzQvMzMzODk4NTcxLWI3YWUxOTkxLTllODEtNDgwOS05NGU4LTNmY2NhNGIzNTdmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2MwZWM3YWRmMjg1YzBiZDVhNmQ1NTVhMWQ4NjI0ZjY5YjI5NjIwMzNjNjM5OTc3ODkwZTNlZDUzZGNmMmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m3_doBjLLoUUhHwhY485gIU4g9BI_E8nS3mFQKiZ_Kw)

I fixed it in my fork (the heart bug). The original code of the swf got corrupted because I had to decrypt it. I injected a little bit of code into the swf (Dimensions). Now it should work again. Does the login problem still persist? Because I tested it with my source files and everything worked like it should. Did you configure everything correctly? Did you for example put in the correct ip into the settings598b.ini (This is the one required for dimensions)?

**Comment by Migueli000** [comment]
it works thanks

**Comment by Michal2SAB** [comment]
The first issue could be a lot of things. From misuse of the hashing algorithm, to stick_arena.php file not working (outdated or too new for your installed PHP version).

The second one is unrelated to this repository as it has to do with a different client (dimensions.swf), which I did not provide. Likely corrupted like the guy said.
